add method

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -81,7 +81,7 @@ jobs:
 
       - name: Test Report
         uses: dorny/test-reporter@v1
-        if: success() || failure() # run this step even if previous step failed
+        if: github.actor != 'dependabot-bot' && (success() || failure()) # run this step even if previous step failed
         with:
           name: Test Report              # Name of the check run which will be created 
           path: src/TestResults/**/*.trx # Path to test results
@@ -90,7 +90,7 @@ jobs:
           list-tests: failed
 
       - name: NuGet Publish
-        if: ${{ github.ref == 'refs/heads/master' }}
+        if: github.ref == 'refs/heads/master'
         shell: pwsh
         run: |
           ./build/pack.ps1 no-restore
@@ -118,7 +118,7 @@ jobs:
 
       - name: Test Report
         uses: dorny/test-reporter@v1
-        if: success() || failure() # run this step even if previous step failed
+        if: github.actor != 'dependabot-bot' && (success() || failure()) # run this step even if previous step failed
         with:
           name: Test Report              # Name of the check run which will be created 
           path: src/TestResults/**/*.trx # Path to test results
@@ -139,7 +139,7 @@ jobs:
           echo $ver
           
       - name: Create Tag
-        if: ${{ github.ref == 'refs/heads/master' }}
+        if: github.ref == 'refs/heads/master'
         uses: richardsimko/update-tag@v1
         with:
           tag_name: ${{ env.VERSION }}
